doc-warnings: no
test-warnings: no
strictness: high
pep8:
    full: true
uses:
    - django
autodetect: yes
ignore-paths:
    - SCREENSHOTS
    - Servus/manage.py
    - Servus/logs
    - Servus/media
ignore-patterns:
    - (^|/)migrations(/|$)
    - (^|/)static(/|$)