doc-warnings: no
test-warnings: no
strictness: high
max-line-length: 127
pep8:
    full: true
uses:
    - django
autodetect: yes
ignore-paths:
    - SCREENSHOTS
    - Servus/manage.py
    - Servus/logs
    - Servus/media
ignore-patterns:
    - (^|/)migrations(/|$)
    - (^|/)static(/|$)
pep257:
    # docstring checking
    run: true
    disable:
        # 1 blank line required before class docstring
        - 'D203